

// get Committee Session 
export const REQUEST_COMMITTEE_SESSION = "REQUEST_COMMITTEE_SESSION";
export const SUCCESS_COMMITTEE_SESSION = "SUCCESS_COMMITTEE_SESSION";
export const FAIL_COMMITTEE_SESSION = "FAIL_COMMITTEE_SESSION";

// post Committee Session  
export const REQUEST_ADD_COMMITTEE_SESSION = "REQUEST_ADD_COMMITTEE_SESSION";
export const SUCCESS_ADD_COMMITTEE_SESSION = "SUCCESS_ADD_COMMITTEE_SESSION";
export const FAIL_ADD_COMMITTEE_SESSION = "FAIL_ADD_COMMITTEE_SESSION";


//terminate session
export const REQUEST_TERMINATE_COMMITTEE_SESSION = "REQUEST_TERMINATE_COMMITTEE_SESSION";
export const SUCCESS_TERMINATE_COMMITTEE_SESSION = "SUCCESS_TERMINATE_COMMITTEE_SESSION";
export const FAIL_TERMINATE_COMMITTEE_SESSION = "FAIL_TERMINATE_COMMITTEE_SESSION";

//ChairPerson  Committee Session 

export const REQUEST_ALL_COMMITTEE_SESSION_CHAIRPOV = "REQUEST_ALL_COMMITTEE_SESSION_CHAIRPOV";
export const SUCCESS_ALL_COMMITTEE_SESSION_CHAIRPOV = "SUCCESS_ALL_COMMITTEE_SESSION_CHAIRPOV";
export const FAIL_ALL_COMMITTEE_SESSION_CHAIRPOV = "FAIL_ALL_COMMITTEE_SESSION_CHAIRPOV";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";