export const REQUEST_DELIGATES = "REQUEST_DELIGATES";
export const SUCCESS_DELIGATES = "SUCCESS_DELIGATES";
export const FAIL_DELIGATES = "FAIL_DELIGATES";
export const CLEAR_DELIGATES = "CLEAR_DELIGATES";

export const REQUEST_DELIGATE_JOIN = "REQUEST_DELIGATE_JOIN";
export const SUCCESS_DELIGATE_JOIN = "SUCCESS_DELIGATE_JOIN";
export const FAIL_DELIGATE_JOIN = "FAIL_DELIGATE_JOIN";

export const REQUEST_DELIGATE_DETAILS = "REQUEST_DELIGATE_DETAILS";
export const SUCCESS_DELIGATE_DETAILS = "SUCCESS_DELIGATE_DETAILS";
export const FAIL_DELIGATE_DETAILS = "FAIL_DELIGATE_DETAILS";

export const SELECT_COMMUNITY_ID = "SELECT_COMMUNITY_ID";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
