// get GSL 
export const REQUEST_GSL = "REQUEST_GSL";
export const SUCCESS_GSL = "SUCCESS_GSL";
export const FAIL_GSL = "FAIL_GSL";

// post GSL 
export const REQUEST_ADD_GSL = "REQUEST_ADD_GSL";
export const SUCCESS_ADD_GSL = "SUCCESS_ADD_GSL";
export const FAIL_ADD_GSL = "FAIL_ADD_GSL";

//get GSL Common Settings
export const REQUEST_GSL_COMMON_SETTINGS="REQUEST_GSL_COMMON_SETTINGS"
export const SUCCESS_GSL_COMMON_SETTINGS = "SUCCESS_GSL_COMMON_SETTINGS";
export const FAIL_GSL_COMMON_SETTINGS = "FAIL_GSL_COMMON_SETTINGS";

//start gsl
export const REQUEST_START_GSL = "REQUEST_START_GSL";
export const SUCCESS_START_GSL = "SUCCESS_START_GSL";
export const FAIL_START_GSL = "FAIL_START_GSL";

//post GSL Common Settings
export const REQUEST_ADD_GSL_COMMON_SETTINGS = "REQUEST_ADD_GSL_COMMON_SETTINGS";
export const SUCCESS_ADD_GSL_COMMON_SETTINGS = "SUCCESS_ADD_GSL_COMMON_SETTINGS";
export const FAIL_ADD_GSL_COMMON_SETTINGS = "FAIL_ADD_GSL_COMMON_SETTINGS";

//Admin 

export const REQUEST_ALL_GSL_CHAIRPOV = "REQUEST_ALL_GSL_CHAIRPOV";
export const SUCCESS_ALL_GSL_CHAIRPOV = "SUCCESS_ALL_GSL_CHAIRPOV";
export const FAIL_ALL_GSL_CHAIRPOV = "FAIL_ALL_GSL_CHAIRPOV";

//save GSL Details
export const REQUEST_SAVE_GSL_DETAILS = "REQUEST_SAVE_GSL_DETAILS";
export const SUCCESS_SAVE_GSL_DETAILS = "SUCCESS_SAVE_GSL_DETAILS";
export const FAIL_SAVE_GSL_DETAILS = "FAIL_SAVE_GSL_DETAILS";

//get GSL Details
export const REQUEST_GET_GSL_DETAILS = "REQUEST_GET_GSL_DETAILS";
export const SUCCESS_GET_GSL_DETAILS = "SUCCESS_GET_GSL_DETAILS";
export const FAIL_GET_GSL_DETAILS = "FAIL_GET_GSL_DETAILS";

//get GSL Info Detail
export const REQUEST_GET_GSL_INFO_DETAILS = "REQUEST_GET_GSL_INFO_DETAILS";
export const SUCCESS_GET_GSL_INFO_DETAILS = "SUCCESS_GET_GSL_INFO_DETAILS";
export const FAIL_GET_GSL_INFO_DETAILS = "FAIL_GET_GSL_INFO_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";