export const REQUEST_MCAUS = "REQUEST_MCAUS";
export const SUCCESS_MCAUS = "SUCCESS_MCAUS";
export const FAIL_MCAUS = "FAIL_MCAUS";

export const REQUEST_ADD_MCAUS = "REQUEST_ADD_MCAUS";
export const SUCCESS_ADD_MCAUS = "SUCCESS_ADD_MCAUS";
export const FAIL_ADD_MCAUS = "FAIL_ADD_MCAUS";

// add MCAUS Data 
export const REQUEST_ADD_MCAUSID = "REQUEST_MCAUSID";
export const SUCCESS_ADD_MCAUSID = "SUCCESS_MCAUSID";
export const FAIL_ADD_MCAUSID = "FAIL_MCAUSID";

//update MCAUS ID 
export const REQUEST_UPDATE_MCAUSID = "REQUEST_UPDATE_MCAUSID";
export const SUCCESS_UPDATE_MCAUSID = "SUCCESS_UPDATE_MCAUSID";
export const FAIL_UPDATE_MCAUSID = "FAIL_UPDATE_MCAUSID";


// get MCAUS Data
export const REQUEST_GET_MCAUSID = "REQUEST_GET_MCAUSID";
export const SUCCESS_GET_MCAUSID = "SUCCESS_GET_MCAUSID";
export const FAIL_GET_MCAUSID = "FAIL_GET_MCAUSID";

// All MCAUS Data
export const REQUEST_ALL_MCAUS_CHAIRPOV = "REQUEST_ALL_MCAUS_CHAIRPOV";
export const SUCCESS_ALL_MCAUS_CHAIRPOV = "SUCCESS_ALL_MCAUS_CHAIRPOV";
export const FAIL_ALL_MCAUS_CHAIRPOV = "FAIL_ALL_MCAUS_CHAIRPOV";

// get chair MCAUS Data
export const REQUEST_SAVE_MCAUS_CHAIRPOV = "REQUEST_SAVE_MCAUS_CHAIRPOV";
export const SUCCESS_SAVE_MCAUS_CHAIRPOV = "SUCCESS_SAVE_MCAUS_CHAIRPOV";
export const FAIL_SAVE_MCAUS_CHAIRPOV = "FAIL_SAVE_MCAUS_CHAIRPOV";

//save mcaus details
export const REQUEST_SAVE_MCAUS_DETAILS = "REQUEST_SAVE_MCAUS_DETAILS";
export const SUCCESS_SAVE_MCAUS_DETAILS = "SUCCESS_SAVE_MCAUS_DETAILS";
export const FAIL_SAVE_MCAUS_DETAILS = "FAIL_SAVE_MCAUS_DETAILS";

//get mcaus details
export const REQUEST_GET_MCAUS_DETAILS = "REQUEST_GET_MCAUS_DETAILS";
export const SUCCESS_GET_MCAUS_DETAILS = "SUCCESS_GET_MCAUS_DETAILS";
export const FAIL_GET_MCAUS_DETAILS = "FAIL_GET_MCAUS_DETAILS";

// save mcaus speaker details
export const REQUEST_SAVE_MCAUS_SPEAKER_DETAILS = "REQUEST_SAVE_MCAUS_SPEAKER_DETAILS";
export const SUCCESS_SAVE_MCAUS_SPEAKER_DETAILS = "SUCCESS_SAVE_MCAUS_SPEAKER_DETAILS";
export const FAIL_SAVE_MCAUS_SPEAKER_DETAILS = "FAIL_SAVE_MCAUS_SPEAKER_DETAILS";

// clear mcaus id
export const CLEAR_MCAUS_ID = "CLEAR_MCAUS_ID";


//get mcaus speaker details
export const REQUEST_GET_MCAUS_SPEAKER_DETAILS = "REQUEST_GET_MCAUS_SPEAKER_DETAILS";
export const SUCCESS_GET_MCAUS_SPEAKER_DETAILS = "SUCCESS_GET_MCAUS_SPEAKER_DETAILS";
export const FAIL_GET_MCAUS_SPEAKER_DETAILS = "FAIL_GET_MCAUS_SPEAKER_DETAILS";



//get MCAUS Info Details
export const REQUEST_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS = "REQUEST_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS";
export const SUCCESS_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS = "SUCCESS_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS";
export const FAIL_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS = "FAIL_GET_MCAUS_DELEGATE_SPEAKER_INFO_DETAILS";

//Update  MCAUS Info Details
export const REQUEST_UPDATE_MCAUS_SPEAKER_INFO_DETAILS = "REQUEST_UPDATE_MCAUS_SPEAKER_INFO_DETAILS";
export const SUCCESS_UPDATE_MCAUS_SPEAKER_INFO_DETAILS = "SUCCESS_UPDATE_MCAUS_SPEAKER_INFO_DETAILS";
export const FAIL_UPDATE_MCAUS_SPEAKER_INFO_DETAILS = "FAIL_UPDATE_MCAUS_SPEAKER_INFO_DETAILS";
// get MCAUS Info Detail  

// export const REQUEST_GET_MCAUS_SPEAKER_INFO_DETAILS = "REQUEST_GET_MCAUS_SPEAKER_INFO_DETAILS";
// export const SUCCESS_GET_MCAUS_SPEAKER_INFO_DETAILS = "SUCCESS_GET_MCAUS_SPEAKER_INFO_DETAILS";
// export const FAIL_GET_MCAUS_SPEAKER_INFO_DETAILS = "FAIL_GET_MCAUS_SPEAKER_INFO_DETAILS";


export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const CLEAR_ERRORS = "CLEAR_ERRORS";