export const REQUEST_COMMITTEE_REPORT = 'REQUEST_COMMITTEE_REPORT'
export const SUCCESS_COMMITTEE_REPORT = 'SUCCESS_COMMITTEE_REPORT'
export const FAIL_COMMITTEE_REPORT = 'FAIL_COMMITTEE_REPORT'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'