export const REQUEST_ROLL_LIST = "REQUEST_ROLL_LIST";
export const SUCCESS_ROLL_LIST = "SUCCESS_ROLL_LIST";
export const FAIL_ROLL_LIST = "FAIL_ROLL_LIST";

export const REQUEST_MARKED_ROLL_LIST = "REQUEST_MARKED_ROLL_LIST";
export const SUCCESS_MARKED_ROLL_LIST = "SUCCESS_MARKED_ROLL_LIST";
export const FAIL_MARKED_ROLL_LIST = "FAIL_MARKED_ROLL_LIST";

export const REQUEST_ROLL_CALL = "REQUEST_ROLL_CALL";
export const SUCCESS_ROLL_CALL = "SUCCESS_ROLL_CALL";
export const FAIL_ROLL_CALL = "FAIL_ROLL_CALL";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
