export const REQUEST_UNMCAUS = "REQUEST_UNMCAUS";
export const SUCCESS_UNMCAUS = "SUCCESS_UNMCAUS";
export const FAIL_UNMCAUS = "FAIL_UNMCAUS";

export const REQUEST_ADD_UNMCAUS = "REQUEST_ADD_UNMCAUS";
export const SUCCESS_ADD_UNMCAUS = "SUCCESS_ADD_UNMCAUS";
export const FAIL_ADD_UNMCAUS = "FAIL_ADD_UNMCAUS";

export const REQUEST_CREATE_UNMCUAS_ID = "REQUEST_CREATE_UNMCUAS_ID";
export const SUCCESS_CREATE_UNMCUAS_ID = "SUCCESS_CREATE_UNMCUAS_ID";
export const FAIL_CREATE_UNMCUAS_ID = "FAIL_CREATE_UNMCUAS_ID";


export const REQUEST_GET_UNMCUAS_ID = "REQUEST_GET_UNMCUAS_ID";
export const SUCCESS_GET_UNMCUAS_ID = "SUCCESS_GET_UNMCUAS_ID";
export const FAIL_GET_UNMCUAS_ID = "FAIL_GET_UNMCUAS_ID";

export const SELECT_CURRENT_UNMCAUS = "SELECT_CURRENT_UNMCAUS";
export const CLEAR_CURRENT_UNMCAUS = "CLEAR_CURRENT_UNMCAUS";


export const REQUEST_ALL_UNMCAUS_CHAIRPOV = "REQUEST_ALL_UNMCAUS_CHAIRPOV";
export const SUCCESS_ALL_UNMCAUS_CHAIRPOV = "SUCCESS_ALL_UNMCAUS_CHAIRPOV";
export const FAIL_ALL_UNMCAUS_CHAIRPOV = "FAIL_ALL_UNMCAUS_CHAIRPOV";

//stop unmcuas
export const REQUEST_FINISH_UNMCAUS = "REQUEST_FINISH_UNMCAUS";
export const SUCCESS_FINISH_UNMCAUS = "SUCCESS_FINISH_UNMCAUS";
export const FAIL_FINISH_UNMCAUS = "FAIL_FINISH_UNMCAUS";

export const CLEAR_MSG = "CLEAR_MSG";
export const CLEAR_ERRORS = "CLEAR_ERRORS";