export const REQUEST_REGISTRATION = "REQUEST_REGISTRATION";
export const SUCCESS_REGISTRATION = "SUCCESS_REGISTRATION";
export const FAIL_REGISTRATION = "FAIL_REGISTRATION";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
export const FAIL_LOGOUT = "FAIL_LOGOUT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
    