// fetch pending marked delegates 
export const REQUEST_PENDING_MARKED_DELEGATES = "REQUEST_PENDING_MARKED_DELEGATES";
export const SUCCESS_PENDING_MARKED_DELEGATES = "SUCCESS_PENDING_MARKED_DELEGATES";
export const FAIL_PENDING_MARKED_DELEGATES = "FAIL_PENDING_MARKED_DELEGATES";

// vote action 
export const REQUEST_DO_VOTE = "REQUEST_DO_VOTE";
export const SUCCESS_DO_VOTE = "SUCCESS_DO_VOTE";
export const FAIL_DO_VOTE = "FAIL_DO_VOTE";

//chair voting
export const REQUEST_DO_CHAIR_VOTE = "REQUEST_DO_CHAIR_VOTE";
export const SUCCESS_DO_CHAIR_VOTE = "SUCCESS_DO_CHAIR_VOTE";
export const FAIL_DO_CHAIR_VOTE = "FAIL_DO_CHAIR_VOTE";

//chair get topics
export const REQUEST_GET_CHAIR_TOPICS = "REQUEST_GET_CHAIR_TOPICS";
export const SUCCESS_GET_CHAIR_TOPICS = "SUCCESS_GET_CHAIR_TOPICS";
export const FAIL_GET_CHAIR_TOPICS = "FAIL_GET_CHAIR_TOPICS";

// get all result chair
export const REQUEST_GET_ALL_RESULT_CHAIR = "REQUEST_GET_ALL_RESULT_CHAIR";
export const SUCCESS_GET_ALL_RESULT_CHAIR = "SUCCESS_GET_ALL_RESULT_CHAIR";
export const FAIL_GET_ALL_RESULT_CHAIR = "FAIL_GET_ALL_RESULT_CHAIR";

// get result chair 
export const REQUEST_GET_RESULT_CHAIR = "REQUEST_GET_RESULT_CHAIR";
export const SUCCESS_GET_RESULT_CHAIR = "SUCCESS_GET_RESULT_CHAIR";
export const FAIL_GET_RESULT_CHAIR = "FAIL_GET_RESULT_CHAIR";


//get passed voting Topic 


// get result chair 
export const REQUEST_GET_PASSED_VOTING_TOPIC_CHAIR = "REQUEST_GET_PASSED_VOTING_TOPIC_CHAIR";
export const SUCCESS_GET_PASSED_VOTING_TOPIC_CHAIR = "SUCCESS_GET_PASSED_VOTING_TOPIC_CHAIR";
export const FAIL_GET_PASSED_VOTING_TOPIC_CHAIR = "FAIL_GET_PASSED_VOTING_TOPIC_CHAIR"


//clear messages
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
